stages:
  - build

job:
  stage: build
  script:
  - git submodule update --init
  - ''
  - echo "Release build..."
  - ''
  - 'Start-Process "cmd.exe" "/c build_sdk.bat"'
  - ''
  - echo "Build success..."
  tags: 
  - my-tag
  except:
  - tags