stages:
  - build

job:
  stage: build
  script:
  - git submodule update --init
  - call "%VS140COMNTOOLS%\vsvars32.bat"
  - ''
  - devenv "astronomy_sdk_vs2015.sln" /rebuild "Release|x64"
  - ''
  - echo "Build success."
  tags: 
  - my-tag
  except:
  - tags