stages:
  - build

job:
  stage: build
  script:
  - git submodule update --init
  - ''
  - echo "Release build..."
  - ''
  - '"C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" /consoleloggerparameters:ErrorsOnly /maxcpucount /nologo /property:Configuration=Release /verbosity:quiet "astronomy_sdk_vs2015.sln"'
  - ''
  - echo "Build success."
  tags: 
  - my-tag
  except:
  - tags