stages:
  - build

vc14_x64_release:
  stage: build
  script:
       - git submodule update --init --recursive
       - .\msbuild_R.ps1 
  tags: 
  - win10-tag
  
vc14_x64_debug:
  stage: build
  script:
       - git submodule update --init --recursive
       - .\msbuild_D.ps1 
  tags: 
  - win10-tag