stages:
  - build

compile.windows.vs2015:
  stage: build
  script:
  - git submodule update --init
  - ''
  - 'call "%VS140COMNTOOLS%VsDevCmd.bat"'
  - ''
  - echo "Release build..."
  - ''
  - 'msbuild astronomy_sdk_vs2015.sln /t:Build /p:Configuration="Release" /p:Platform="x64"'
  - ''
  - echo "Build success."
  tags: 
  - my-tag
  except:
  - tags