stages:
  - build

job:
  stage: build
  script:
  - git submodule update --init
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\vsvars32.bat"
  - ''
  - devenv "astronomy_sdk_vs2015.sln" /rebuild "Release|x64"
  - ''
  - echo "Build success."
  tags: 
  - my-tag
  except:
  - tags