stages:
  - build

job:
  stage: build
  script:
  - git submodule update --init
  - call "%VS140COMNTOOLS%\vsvars32.bat"
  - ''
  - devenv "%CD%\SearchAlgCpp\C++\ODSW_CPP\ODSW_CPP.sln" /rebuild "Release|x64"
  - '"c:\nuget\nuget.exe" restore "TerminalClone.sln"'
  - ''
  - echo "Build success."
  tags: 
  - my-tag
  except:
  - tags